// AXCtl.idl : type library source for ActiveX Control project.

// This file will be processed by the MIDL compiler tool to
// produce the type library (AXCtl.tlb) that will become a resource in
// AXCtl.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(7292663B-606A-487A-8FD8-CEB23D37ECAD), version(1.0),
  control ]
library AXCtlLib
{
	importlib(STDOLE_TLB);

	//  Primary dispatch interface for CAXCtlCtrl
	[ 
		uuid(1A614CEA-0184-4015-9F97-13192CD0E656)	
	]
	dispinterface _DAXCtl
	{
		properties:
		methods:
			[id(1)] void Fuck2(void);
	};

	//  Event dispatch interface for CAXCtlCtrl

	[ 
		uuid(8ADCF049-FD89-4449-8451-00D7F0356543)	
	]
	dispinterface _DAXCtlEvents
	{
		properties:
			//  Event interface has no properties

		methods:
	};

	//  Class information for CAXCtlCtrl
	[
		uuid(14038829-EA6F-41D6-862C-6D146D7AC3A0)
	]
	coclass AXCtl
	{
		[default] dispinterface _DAXCtl;
		[default, source] dispinterface _DAXCtlEvents;
	};

};
